routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/contact', 'ContactController@show');
Route::post('/contact',  'ContactController@mailToAdmin'); 

Route::get('/', 'HomeController@index')->name('home');

// User Routes
Route::group(['namespace' => 'User'], function(){

  Route::get('home', 'HomeController@index')->name('inicio');

  Route::get('sobre', 'MenusController@sobre')->name('sobre');

  Route::get('vantagens', 'MenusController@vantagens')->name('vantagens');
    
  Route::get('subscricao', 'MenusController@subscricao')->name('subscricao');
    
  Route::get('resultados', 'MenusController@resultados')->name('resultados');

  Route::get('post/{post}', 'PostController@post')->name('post');

  Route::get('post/tag/{tag}', 'HomeController@tag')->name('tag');

  Route::get('post/category/{category}', 'HomeController@category')->name('category');

});


Route::group(['namespace' => 'Admin'], function(){

  Route::get('admin/home', 'HomeController@index')->name('admin.home');

  // Users Routes

  Route::resource('admin/user', 'UserController');

  // Post Routes

  Route::resource('admin/post', 'PostController');

  // Tag Routes

  Route::resource('admin/tag', 'TagController');

  // Category Routes

  Route::resource('admin/category', 'CategoryController');

  // Admin Auth Route

  Route::get('admin-login', 'Auth\LoginController@showLoginForm')->name('admin.login');

  Route::post('admin-login', 'Auth\LoginController@Login');


});



  Auth::routes();

  // Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\admin\admin;
use App\Model\user\User;

class UserController extends Controller
{


  /**
   * Create a new controller instance.
   *
   * @return void
   */
  public function __construct()
  {
      $this->middleware('auth:admin');
  }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users =  User::all();
        return view ('admin.user.show', compact('users'));


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $users = User::find($id);
        return view('admin.user.edit', compact('users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        

        $users = User::find($id);
        $users->status = $request->status;
        $users->save();

        return redirect(route('user.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/HomeController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\user\post;
use App\Model\user\category;
use App\Model\user\tag;

class HomeController extends Controller
{

  public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
      $posts = post::where('status', 1)->orderBy('created_at', 'DESC')->paginate(3);
      return view('user.home', compact('posts'));
    }

    public function tag(tag $tag)
    {
      $posts = $tag->posts();
      return view('user.home', compact('posts'));
    }

    public function category(category $category)
    {
      $posts = $category->posts();
      return view('user.home', compact('posts'));
    }
}

app/Http/Controllers/User/MenusController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class MenusController extends Controller
{
      public function sobre()
    {
      return view ('user.sobre');
    }

     public function vantagens()
    {
      return view ('user.vantagens');
    }
    
    public function subscricao()
    {
        return view ('user.subscricao');
    }
    
    public function resultados() 
    {
        return view ('user.resultados');
    }
    
}

app/Http/Controllers/User/PostController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\user\post;

class PostController extends Controller
{
    public function post(post $post)
    {

      return view ('user.post', compact('post'));
    }
}

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.app')

@section('main-content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Text Editors
      <small>Advanced form element</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="#">Forms</a></li>
      <li class="active">Editors</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-md-12">

        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Edit User</h3>
          </div>

          @include('includes.messages')

          <!-- /.box-header -->
          <!-- form start -->
          <form role="form" action="{{ route('user.update', $users->id) }}" method="post">
            {{ csrf_field() }}
            {{ method_field('PATCH') }}
            <div class="box-body">
              <div class="col-lg-offset-3 col-lg-6">

              <div class="checkbox">
                  <label>
                    <input type="checkbox" name="status" value="1" @if($users->status == 1) {{'checked'}} @endif> Premium
                  </label>
                </div>

              <br>

            <div class="form-group">
              <button type="submit" class="btn btn-primary">Submit</button>
              <a href='{{ route('user.index') }}' class="btn btn-warning">Show Users</a>
            </div>
          </form>
        </div>
        <!-- /.box -->


      </div>
      <!-- /.col-->
    </div>
    <!-- ./row -->
  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->


@endsection

resources/views/admin/user/show.blade.php
@extends('admin.layouts.app')

@section('headSection')

<link rel="stylesheet" href="{{ asset('admin/plugins/datatables/dataTables.bootstrap.css') }}">

@endsection

@section('main-content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Admin
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="#">Examples</a></li>
      <li class="active">Blank page</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">

    <!-- Default box -->
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">Users</h3>


        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
            <i class="fa fa-minus"></i></button>
          <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
            <i class="fa fa-times"></i></button>
        </div>
      </div>
      <div class="box-body">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Data Table With Full Features</h3>
          </div>
          <!-- /.box-header -->
          <div class="box-body">
            <table id="example1" class="table table-bordered table-striped">
              <thead>
              <tr>
                <th>S.No</th>
                <th>User Name</th>
                <th>Status</th>
                <th>Email</th>
                <th>Edit</th>
                <th>Delete</th>
              </tr>
              </thead>
              <tbody>

                @foreach ($users as $user)

                <tr>
                  <td>{{ $loop->index + 1 }}</td>
                  <td>{{ $user->name }}</td>
                  <td>{{ $user->status }}</td>
                  <td>{{ $user->email }}</td>
                   <td><a href="{{ route('user.edit',$user->id) }}"><span class="glyphicon glyphicon-edit"</span></a></td>
                  <td>

                    <form id="delete-form-{{ $user->id }}" method="post" action="{{ route('user.destroy', $user->id) }}" style="display: none">

                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}

                    </form>

                    <a href="" onclick="if(confirm('Are you sure you want to delete this?'))
                    {
                      event.preventDefault();
                      document.getElementById('delete-form-{{ $user->id }}').submit();
                    }
                    else
                    {
                      event.preventDefault();
                    }"><span class="glyphicon glyphicon-trash"></span></a>

                  </td>
                </tr>

                @endforeach

              </tbody>
              <tfoot>
              <tr>
                <th>S.No</th>
                <th>User Name</th>
                <th>Status</th>
                <th>Edit</th>
                <th>Delete</th>
              </tr>
              </tfoot>
            </table>
          </div>
          <!-- /.box-body -->
        </div>
      </div>
      <!-- /.box-body -->
      <div class="box-footer">
        Footer
      </div>
      <!-- /.box-footer-->
    </div>
    <!-- /.box -->

  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection

@section('footerSection')

<script src="{{ asset('admin/plugins/datatables/jquery.dataTables.min.js') }}"></script>

<script src="{{ asset('admin/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>

<script>
  $(function () {
    $("#example1").DataTable();

  });
</script>

@endsection